version: "3.8"

services:
  dqa:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
        - ../../:/home/challenger/dqa
    ports:
        - 8000:8000